import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}


export const commonPasswords = [
  "password",
  "football",
  "computer",
  "baseball",
  "sunshine",
  "princess",
  "butterfly",
  "mountain",
  "elephant",
  "chocolate",
  "homework",
  "hospital",
  "children",
  "notebook",
  "birthday",
  "baseball",
  "vacation",
  "daughter",
  "learning",
  "familiar",
  "building",
  "language",
  "exercise",
  "medicine",
  "absolute",
  "training",
  "favorite",
  "friendly",
  "remember",
  "research",
  "anything",
  "possible",
  "solution",
  "stranger",
  "learning",
  "carefree",
  "location",
  "marriage",
  "generate",
  "dominate",
  "apparent",
  "happiest",
  "valuable",
  "domestic",
  "concrete",
  "separate",
  "engineer",
  "guidance",
  "handsome",
  "pleasant"
];
