// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blstljercjtydsxjkebd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsc3RsamVyY2p0eWRzeGprZWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDA0NDQsImV4cCI6MjA3MzA3NjQ0NH0.i1eOz6kCyb3tD7_SyW45T0ATenyN-wq7Dufvs-VLvdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});